type: app
name: hello-rva23
base: core26
license: GPL-3.0
build-base: devel
source-code: https://github.com/xypron/hello-rva23.git
website: https://github.com/xypron/hello-rva23
version: '2.12-1'
summary: GNU Hello requiring RVA23S64 support
description: |
  Hello-rva23 prints a friendly greeting.

  Since Ubuntu 25.10 support for RVA23S64 is required on the RISC-V
  architecture. This also applies to all snaps built using core 26.04.

  This instance of a hello snap has been specifically built with the
  RVA23S64 requirement.
grade: devel
confinement: strict
platforms:
  riscv64:
    build-on: riscv64
    build-for: riscv64

apps:
  hello:
    command: usr/bin/hello

parts:
  gnu-hello:
    source: .
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr/
